server:
  port: 19097
spring:
  application:
    name: payments-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/limito-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html # 기본값
  config:
    import: optional:file:.env[.properties]
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
# 포트원 설정
portone:
  channel-key: ${PORTONE_CHANNEL_KEY}
  store-id: ${PORTONE_STORE_ID}
  api-secret: ${PORTONE_API_SECRET}
  base-url: https://api.portone.io
# 로깅 설정
logging:
  level:
    com.limito.payment: INFO
    #    org.springframework.web: error
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
feign:
  order-service:
    url: http://localhost:19096
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics